databases:
  - name: locallibrary
    databaseName: locallibrary
    user: locallibrary

services:
  - type: web
    name: locallibrary
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn locallibrary.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: locallibrary
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
